# fly.toml app configuration file generated for mithril-rem on 2024-06-08T01:57:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mithril-rem'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
